// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ConfirmModal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<dialog x-data=\"nativeConfirmModal()\" x-init=\"$watch('isOpen', value => value ? $el.showModal() : $el.close())\" x-show=\"isOpen\" x-on:open-confirm.window=\"open($event)\" x-on:close=\"cancel()\" class=\"custom-modal p-6 rounded shadow-xl border border-app-acc bg-app-sec text-app-txt fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 backdrop:backdrop-blur-sm backdrop:bg-black/50\"><form method=\"dialog\" class=\"flex flex-col gap-4\"><h3 x-text=\"title\" class=\"text-xl font-bold capitalize\">Confirm Action</h3><p x-text=\"message\" class=\"text-sm opacity-90\"></p><div class=\"flex justify-end gap-3 mt-4\"><button type=\"button\" @click=\"cancel()\" class=\"px-4 py-2 bg-gray-400 rounded text-app-dom cursor-pointer\">Cancel</button> <button type=\"button\" @click=\"confirm()\" class=\"px-4 py-2 bg-red-600 rounded text-white cursor-pointer\">Proceed</button></div></form></dialog><script>\n    function nativeConfirmModal() {\n        return {\n            isOpen: false,\n            title: 'Confirm',\n            message: '',\n            htmxEvent: null,\n\n            open(e) {\n                this.title = e.detail.title || 'Confirm';\n                this.message = e.detail.message || 'Are you sure?';\n                this.htmxEvent = e.detail.targetEvent;\n                this.isOpen = true;\n            },\n            cancel() {\n                this.isOpen = false;\n                this.htmxEvent = null;\n            },\n            confirm() {\n                this.isOpen = false;\n                if (this.htmxEvent) {\n                    this.htmxEvent.detail.confirmed = true;\n                    this.htmxEvent.detail.issueRequest();\n                }\n            }\n        }\n    }\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
