// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Location struct {
	ID              int64
	Title           string
	ImageSrc        string
	ImageAlt        string
	Lat             float64
	Lon             float64
	IsDreamLocation int64
}
