// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const listAvailableLocations = `-- name: ListAvailableLocations :many
SELECT id, title, image_src, image_alt, lat, lon, is_dream_location FROM locations
WHERE is_dream_location = 0
ORDER BY title
`

func (q *Queries) ListAvailableLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listAvailableLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ImageSrc,
			&i.ImageAlt,
			&i.Lat,
			&i.Lon,
			&i.IsDreamLocation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDreamLocations = `-- name: ListDreamLocations :many
SELECT id, title, image_src, image_alt, lat, lon, is_dream_location FROM locations
WHERE is_dream_location = 1
ORDER BY title
`

func (q *Queries) ListDreamLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listDreamLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ImageSrc,
			&i.ImageAlt,
			&i.Lat,
			&i.Lon,
			&i.IsDreamLocation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDreamLocationStatus = `-- name: SetDreamLocationStatus :exec
UPDATE locations
SET is_dream_location = ?
WHERE id = ?
`

type SetDreamLocationStatusParams struct {
	IsDreamLocation int64
	ID              int64
}

func (q *Queries) SetDreamLocationStatus(ctx context.Context, arg SetDreamLocationStatusParams) error {
	_, err := q.db.ExecContext(ctx, setDreamLocationStatus, arg.IsDreamLocation, arg.ID)
	return err
}
